addSbtPlugin("com.dwijnand"      % "sbt-dynver"      % "4.1.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "5.6.0")
addSbtPlugin("io.spray"          % "sbt-revolver"    % "0.9.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"    % "2.4.2")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"   % "1.6.1")
addSbtPlugin("org.wartremover"   % "sbt-wartremover" % "2.4.16")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"    % "0.14.10")
